bezoar/web/router.ex
defmodule Bezoar.Router do
  use Bezoar.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Bezoar do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/admin", Bezoar do
    pipe_through :browser # Use the default browser stack

    resources "/players", PlayerController
    resources "/champs", ChampController
    resources "/skills", SkillController
  end

  # Other scopes may use custom stacks.
  scope "/json", Bezoar do
     pipe_through :api
    
  end
end

bezoar/web/models/player.ex
defmodule Bezoar.Player do
  use Bezoar.Web, :model
  import Ecto.Query

  schema "players" do
    has_many :champs, Bezoar.Champ

    field :name, :string
    field :email, :string
    field :secret, :string
    field :gold, :integer

    timestamps
  end

  @required_fields ~w(name email secret gold)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :invalid) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end

  def get_by_name(name) do
    Bezoar.Repo.one!(Bezoar.Player |> where([p], p.name == ^name))
  end

  def name_to_id(name) do
    get_by_name(name).id
  end

  def get_team(player_id) do
    pp = Bezoar.Repo.one!(Bezoar.Player 
          |> where([p], p.id == ^player_id)
          |> preload(champs: :skills))
    Enum.map(pp.champs, &Bezoar.Champ.to_map/1)
  end

  def to_map(player) do
    %{ id: player.id, name: player.name, }
  end
end

bezoar/web/controllers/player_controller.ex
defmodule Bezoar.PlayerController do
  use Bezoar.Web, :controller

  alias Bezoar.Player

  plug :scrub_params, "player" when action in [:create, :update]

  def index(conn, _params) do
    players = Repo.all(Player)
    render(conn, "index.html", players: players)
  end

  def new(conn, _params) do
    changeset = Player.changeset(%Player{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"player" => player_params}) do
    changeset = Player.changeset(%Player{}, player_params)

    case Repo.insert(changeset) do
      {:ok, _player} ->
        conn
        |> put_flash(:info, "Player created successfully.")
        |> redirect(to: player_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    player = Repo.get!(Player, id) |> Repo.preload(:champs)
    render(conn, "show.html", player: player)
  end

  def edit(conn, %{"id" => id}) do
    player = Repo.get!(Player, id)
    changeset = Player.changeset(player)
    render(conn, "edit.html", player: player, changeset: changeset)
  end

  def update(conn, %{"id" => id, "player" => player_params}) do
    player = Repo.get!(Player, id)
    changeset = Player.changeset(player, player_params)

    case Repo.update(changeset) do
      {:ok, player} ->
        conn
        |> put_flash(:info, "Player updated successfully.")
        |> redirect(to: player_path(conn, :show, player))
      {:error, changeset} ->
        render(conn, "edit.html", player: player, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    player = Repo.get!(Player, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(player)

    conn
    |> put_flash(:info, "Player deleted successfully.")
    |> redirect(to: player_path(conn, :index))
  end
end

bezoar/web/views/player_view.ex
defmodule Bezoar.PlayerView do
  use Bezoar.Web, :view
end

bezoar/web/templates/player/edit.html.eex
<h2>Edit player</h2>

<%= render "form.html", changeset: @changeset,
                        action: player_path(@conn, :update, @player) %>

<%= link "Back", to: player_path(@conn, :index) %>

bezoar/web/templates/player/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :secret, class: "control-label" %>
    <%= text_input f, :secret, class: "form-control" %>
    <%= error_tag f, :secret %>
  </div>

  <div class="form-group">
    <%= label f, :gold, class: "control-label" %>
    <%= number_input f, :gold, class: "form-control" %>
    <%= error_tag f, :gold %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

bezoar/web/templates/player/index.html.eex
<h2>Listing players</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Secret</th>
      <th>Gold</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for player <- @players do %>
    <tr>
      <td><%= player.name %></td>
      <td><%= player.email %></td>
      <td><%= player.secret %></td>
      <td><%= player.gold %></td>

      <td class="text-right">
        <%= link "Show", to: player_path(@conn, :show, player), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: player_path(@conn, :edit, player), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: player_path(@conn, :delete, player), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New player", to: player_path(@conn, :new) %>

bezoar/web/templates/player/new.html.eex
<h2>New player</h2>

<%= render "form.html", changeset: @changeset,
                        action: player_path(@conn, :create) %>

<%= link "Back", to: player_path(@conn, :index) %>

bezoar/web/templates/player/show.html.eex
<h2>Show player</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @player.name %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @player.email %>
  </li>

  <li>
    <strong>Secret:</strong>
    <%= @player.secret %>
  </li>

  <li>
    <strong>Gold:</strong>
    <%= @player.gold %>
  </li>
</ul>

<p><strong>Champs</strong></p>

<ul>
  <%= Enum.map @player.champs, fn cc -> %>
    <li><%= link cc.name, to: champ_path(@conn, :show, cc) %></li>
  <% end %>
</ul>

<%= link "Edit", to: player_path(@conn, :edit, @player) %> |
<%= link "Back", to: player_path(@conn, :index) %>