bezoar/web/router.ex
defmodule Bezoar.Router do
  use Bezoar.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Bezoar do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/admin", Bezoar do
    pipe_through :browser # Use the default browser stack

    resources "/players", PlayerController
    resources "/champs", ChampController
    resources "/skills", SkillController
  end

  # Other scopes may use custom stacks.
  scope "/json", Bezoar do
     pipe_through :api
    
  end
end

bezoar/web/models/champ.ex
defmodule Bezoar.Champ do
  use Bezoar.Web, :model

  schema "champs" do
    belongs_to :player, Bezoar.Player
    has_many :champ_skills, Bezoar.ChampSkill, on_delete: :delete_all
    has_many :skills, through: [:champ_skills, :skill]

    field :name, :string
    field :hp, :integer
    field :hp_max, :integer
    field :hp_base, :integer

    timestamps
  end

  @required_fields [:name, :hp_base, :hp, :hp_max, :player_id]
  @optional_fields []

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :invalid) do
    model
    |> cast(params, @required_fields ++ @optional_fields)
    |> validate_required(@required_fields)
    |> foreign_key_constraint(:player_id)
    |> cast_assoc(:champ_skills, required: false)
  end

  def to_map(champ) do
    champ
    |> Map.from_struct
    |> Map.delete(:__meta__)
    |> skills_to_maps 
    |> Map.drop([:champ_skills, :updated_at, :inserted_at, :player])
    |> Map.put(:dead, false)
    |> Map.put(:effects, [])
  end

  defp skills_to_maps(champ) do
    %{champ | skills: Enum.map(champ.skills, &Bezoar.Skill.to_map/1)}
  end
end

bezoar/web/controllers/champ_controller.ex
defmodule Bezoar.ChampController do
  use Bezoar.Web, :controller

  alias Bezoar.Champ

  plug :scrub_params, "champ" when action in [:create, :update]

  def index(conn, _params) do
    champs = Repo.all(Champ)
    render(conn, "index.html", champs: champs)
  end

  def new(conn, _params) do
    changeset = Champ.changeset(%Champ{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"champ" => champ_params}) do
    changeset = Champ.changeset(%Champ{}, champ_params)

    case Repo.insert(changeset) do
      {:ok, _champ} ->
        conn
        |> put_flash(:info, "Champ created successfully.")
        |> redirect(to: champ_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    champ = Repo.get!(Champ, id) |> Repo.preload(:skills)
    render(conn, "show.html", champ: champ)
  end

  def edit(conn, %{"id" => id}) do
    champ = Repo.get!(Champ, id) |> Repo.preload(:champ_skills)
    changeset = Champ.changeset(champ)
    render(conn, "edit.html", champ: champ, changeset: changeset)
  end

  def update(conn, %{"id" => id, "champ" => champ_params}) do
    champ = Repo.get!(Champ, id) |> Repo.preload(:champ_skills)
    changeset = Champ.changeset(champ, champ_params)

    case Repo.update(changeset) do
      {:ok, champ} ->
        conn
        |> put_flash(:info, "Champ updated successfully.")
        |> redirect(to: champ_path(conn, :show, champ))
      {:error, changeset} ->
        render(conn, "edit.html", champ: champ, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    champ = Repo.get!(Champ, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(champ)

    conn
    |> put_flash(:info, "Champ deleted successfully.")
    |> redirect(to: champ_path(conn, :index))
  end
end

bezoar/web/views/champ_view.ex
defmodule Bezoar.ChampView do
  use Bezoar.Web, :view
end

bezoar/web/templates/champ/edit.html.eex
<h2>Edit champ</h2>

<%= render "form.html", changeset: @changeset,
                        action: champ_path(@conn, :update, @champ) %>

<%= link "Back", to: champ_path(@conn, :index) %>

bezoar/web/templates/champ/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :hp, class: "control-label" %>
    <%= number_input f, :hp, class: "form-control" %>
    <%= error_tag f, :hp %>
  </div>

  <div class="form-group">
    <%= label f, :hp_max, class: "control-label" %>
    <%= number_input f, :hp_max, class: "form-control" %>
    <%= error_tag f, :hp_max %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

bezoar/web/templates/champ/index.html.eex
<h2>Listing champs</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Hp</th>
      <th>Hp max</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for champ <- @champs do %>
    <tr>
      <td><%= champ.name %></td>
      <td><%= champ.hp %></td>
      <td><%= champ.hp_max %></td>

      <td class="text-right">
        <%= link "Show", to: champ_path(@conn, :show, champ), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: champ_path(@conn, :edit, champ), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: champ_path(@conn, :delete, champ), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New champ", to: champ_path(@conn, :new) %>

bezoar/web/templates/champ/new.html.eex
<h2>New champ</h2>

<%= render "form.html", changeset: @changeset,
                        action: champ_path(@conn, :create) %>

<%= link "Back", to: champ_path(@conn, :index) %>

bezoar/web/templates/champ/show.html.eex
<h2>Show champ</h2>

<ul>
  <li>
    <strong>Name:</strong>
    <%= @champ.name %>
  </li>
  <li>
    <strong>Base Hp:</strong>
    <%= @champ.hp_base %>
  </li>
  <li>
    <strong>Current Hp:</strong>
    <%= @champ.hp %>
  </li>
  <li>
    <strong>Hp max:</strong>
    <%= @champ.hp_max %>
  </li>
</ul>

<p><strong>Skills</strong></p>

<ul>
  <%= Enum.map @champ.skills, fn ss -> %>
  <li><%= link ss.name, to: skill_path(@conn, :show, ss) %></li>
  <% end %>
</ul>

<%= link "Edit", to: champ_path(@conn, :edit, @champ) %>
<%= link "Back", to: champ_path(@conn, :index) %>